-- Baseline for environments where Hibernate ddl-auto already created this table.
-- baseline-on-migrate marks this version as done without running it there, so this
-- only actually executes against a brand-new database.
CREATE TABLE IF NOT EXISTS menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurant_id BIGINT NOT NULL,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    price NUMERIC(10, 2) NOT NULL,
    category VARCHAR(60),
    available BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);
CREATE INDEX IF NOT EXISTS idx_menu_item_restaurant_id ON menu_items (restaurant_id);
CREATE INDEX IF NOT EXISTS idx_menu_item_available ON menu_items (available);
