spring:
  profiles:
    active: docker
  application:
    name: api-gateway
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://config-server:8888}
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 6
        max-interval: 2000
        multiplier: 1.1
    discovery:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://service-discovery:8761}/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890123456789012345678901234567890}

logging:
  level:
    com.ifoodclone.gateway: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.web.reactive: INFO
