apiVersion: v2
name: ifood-infra
description: Umbrella chart for the iFood Clone infrastructure dependencies (PostgreSQL, MongoDB, Redis, Kafka)
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "13.4.4"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: mongodb
    version: "15.6.26"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mongodb.enabled
  - name: redis
    version: "19.6.4"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: kafka
    version: "29.3.14"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled
