-- Not part of the V1 baseline: this table doesn't exist yet on already-deployed
-- databases, so unlike V1 it must actually run there too (baseline only skips
-- versions <= the baseline version, which defaults to 1).
CREATE TABLE IF NOT EXISTS verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(100) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users (id),
    type VARCHAR(30) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    used_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    CONSTRAINT uk_verification_tokens_token UNIQUE (token)
);
CREATE INDEX IF NOT EXISTS idx_verification_token ON verification_tokens (token);
CREATE INDEX IF NOT EXISTS idx_verification_token_user ON verification_tokens (user_id);
