-- Baseline for environments where Hibernate ddl-auto already created these tables.
-- baseline-on-migrate marks this version as done without running it there, so this
-- only actually executes against a brand-new database. The status/payment_method
-- CHECK constraints intentionally include the full current OrderStatus/PaymentMethod
-- enums (the live DB's constraint predates OUT_FOR_DELIVERY/DELIVERED and is stale,
-- but baseline-on-migrate means this file won't touch it there).
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    restaurant_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('CART', 'PENDING_PAYMENT', 'CONFIRMED', 'PAYMENT_FAILED', 'PREPARING', 'OUT_FOR_DELIVERY', 'DELIVERED', 'CANCELLED')),
    delivery_address VARCHAR(255),
    payment_method VARCHAR(20) CHECK (payment_method IN ('CREDIT_CARD', 'PIX')),
    total_amount NUMERIC(10, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);
CREATE INDEX IF NOT EXISTS idx_order_user_id ON orders (user_id);
CREATE INDEX IF NOT EXISTS idx_order_restaurant_id ON orders (restaurant_id);
CREATE INDEX IF NOT EXISTS idx_order_status ON orders (status);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders (id),
    menu_item_id BIGINT NOT NULL,
    item_name VARCHAR(120) NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(10, 2) NOT NULL,
    notes VARCHAR(255)
);
