{{- if (index .Values "kube-prometheus-stack" "enabled") }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ifood-grafana-datasources
  labels:
    grafana_datasource: "1"
data:
  loki-jaeger-datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: http://loki:3100
        isDefault: false
      - name: Jaeger
        type: jaeger
        access: proxy
        url: http://jaeger:16686
        isDefault: false
{{- end }}
