-- Baseline for environments where Hibernate ddl-auto already created this table.
-- baseline-on-migrate marks this version as done without running it there, so this
-- only actually executes against a brand-new database.
CREATE TABLE IF NOT EXISTS restaurants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500),
    cuisine_type VARCHAR(60) NOT NULL,
    address VARCHAR(255),
    phone VARCHAR(20),
    owner_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6)
);
CREATE INDEX IF NOT EXISTS idx_restaurant_name ON restaurants (name);
CREATE INDEX IF NOT EXISTS idx_restaurant_cuisine_type ON restaurants (cuisine_type);
CREATE INDEX IF NOT EXISTS idx_restaurant_owner_id ON restaurants (owner_id);
CREATE INDEX IF NOT EXISTS idx_restaurant_active ON restaurants (active);
