apiVersion: v2
name: ifood-observability
description: Observability stack for the iFood Clone cluster (metrics, traces, logs)
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: "^60.0.0"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: kube-prometheus-stack.enabled
  - name: loki
    version: "^5.0.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: loki.enabled
  - name: promtail
    version: "^6.0.0"
    repository: "https://grafana.github.io/helm-charts"
    condition: promtail.enabled
