nameOverride: config-server
springProfile: native

image:
  repository: ghcr.io/mayconaraujosantos/takeoutfood_ecommerce/config-server
  tag: fef223984dad20d282663ecc8e57323ecae312f6

service:
  port: 8888
  targetPort: 8888

probes:
  path: /actuator/health
  initialDelaySeconds: 20

serviceDiscovery:
  enabled: false
