nameOverride: config-server
springProfile: native

image:
  repository: ghcr.io/mayconaraujosantos/takeoutfood_ecommerce/config-server
  tag: c9ad489035a777c6a7eaa8c0051bbd75088fc5d9

service:
  port: 8888
  targetPort: 8888

probes:
  path: /actuator/health
  initialDelaySeconds: 20

serviceDiscovery:
  enabled: false
