spring:
  application:
    name: review-service
  profiles:
    active: docker
  config:
    import: "optional:configserver:http://config-server:8888"
  cloud:
    config:
      enabled: true
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: false
      retry:
        initial-interval: 2000
        max-attempts: 6
        max-interval: 10000

server:
  port: 8089

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

logging:
  level:
    com.ifoodclone: DEBUG
    org.springframework.cloud: DEBUG
